### ISSUE TITLE
Pre-trained models need access pproval

### ISSUE THREAD

**Issue by aabsz** [chenhaowen01/srnn_human_motion_predict_for_ros#1]
Hi,

Pre-trained models need access approval. I have requested, but seems my request won't be approved? :-((((

**Comment by xnhw01** [comment]
This project is just a ROS wrapper of SRNN, so I'm sorry I don't have rights to these model files. Please ask the original author of SRNN for permission.

**Comment by aabsz** [comment]
Tnx for the prompt reply.
Yes, you're right. I've asked them for permission. hope to get an answer soon.
I want to use your ROS wrapper and apply it to my custom prediction model. I need the pre-trained model to understand what is exactly happening in the wrapper.
